### ISSUE TITLE
build in subdirectory

### ISSUE THREAD

**Issue by smhg** [anthonyshort/grunt-component-build#10]
When I set up a component task with a `base` option because the component.json I want to use is in a subdirectory, I end up with this error:
**failed to lookup "source"'s dependency "xxx"**

Now, when I look at tasks/component.js, it does
`var config = require( path.resolve(this.data.base, 'component.json') );`
to get the component.json file, using the `base` option. Good.

But next `config.scripts` gets expanded and this seems to be done against the directory where grunt is run (thus nothing is found and scripts becomes an empty array).
As far as I understand this a bit, a `cwd` option should be passed to `grunt.file.expand`.

Am I approaching this the wrong way?

**Comment by kewah** [comment]
You are right. I will take a look later in the day to fix it

**Comment by kewah** [comment]
I'll merge it with the master branch once I have written the tests for this option and @anthonyshort has validated my changes ;)

**Comment by smhg** [comment]
Thx for the quick responses!

I tried out your branch with the issue I'm having and it does not solve it.
I didn't investigate properly (I'm lacking a lot of knowledge about component/grunt).

My simplified set-up is:

```
project root
+-package.json
+-Gruntfile.js
|
+-part of project subdirectory
|  +-component.json
|
+-other part of project subdirectory
|  +-component.json
```

My project has a few separate parts which all are a separate component builds.
The idea was to make separate component tasks in grunt and reuse them in a grunt watch task.

If I got it right a `base` option is basically the only thing required to make this work?
This does take care of finding the component.json's, but finding the components (dependencies) mentioned in it results in the **failed lookup** error.

I might very well be making wrong assumptions though.

**Comment by smhg** [comment]
I've been looking into this a bit more and for my directory structure above I would have this grunt task config:

``` javascript
component: {
    partOfProject: {
        base: 'part/of/project/subdirectory',
        output: 'build',
        config: 'component.json'
    },
    otherPartOfProject: {
        base: 'other/part/of/project/subdirectory',
        output: 'build',
        config: 'component.json'
    }
}
```

`config` (and possibly `output` too?) is optional. So in this case only `base` is necessary, right?

If my assumptions are right, there seems to be something strange in tasks/component.js:
- The Builder.js constructor should be passed the path of component.json. Currently the dirname of the `config` property is used. Isn't that a strange choice? Shouldn't the `base` property be used? Or rather both concatenated?
- The contents of component.json are read using only the `base` property. Shouldn't this follow the same logic as the previous point?
- After the above is streamlined, I still get the _failed lookup_ error for each dependency in component.json. If I interpreted Builder.js right: dependencies can only be found using `builder.addLookup`? Even if they are in the default components subdirectory. So addLookup needs to be called with either path from the previous points concatenated with 'components' if dependencies are present.
- Once the correct directory is passed to the Builder.js constructor, you don't seem to need to prepend any directory to the paths in the `scripts` property in component.json.

This is just my experience to make the above work. I've only tested this with building JS scripts. Not with templates or styles.

**Comment by anthonyshort** [comment]
I have been meaning to clean up the options and paths. It shouldn't be too hard to get this working correctly. You're right about passing the path to the builder. Feel free to fork and submit a pull request if you can get it working a bit nicer. I'll take a good look at it soon. Although @kewah will probably get to it first :)

**Comment by smhg** [comment]
It is ungrateful, but I started a new approach from scratch with the intention to use component-builder.js but I ended up with a wrapper around component(1): https://github.com/smhg/grunt-component

It calls component with grunt.util.spawn. This way you can trust on component(1) for all the path/options handling and new options are immediately available (assuming builder.js and component(1) are maintained simultaneous). Of course you can do more than only building this way (e.g. installing dependencies for your test).

I am not sure, but there might be a way to just spawn from your Gruntfile.js and eliminate the need for this task all-together?

**Comment by kewah** [comment]
> new options are immediately available

It's true that it has some advantages :)

If you just want to wrap `component(1)`, I don't think that a new plugin is necessary. You can use, for example, [grunt-shell](https://github.com/sindresorhus/grunt-shell).

I updated the patch based on your feedback. It works on my local tests, I still have not written tests.
