### ISSUE TITLE
Use component-build to generate source map URLs when in dev mode

### ISSUE THREAD

**Issue by sankargorthi** [anthonyshort/grunt-component-build#24]
https://github.com/component/component/issues/85

This change adds source maps to the component build output. Could this builder invoke that to generate source maps?

**Comment by sankargorthi** [comment]
~~I suppose this would mean updating component-builder to `~0.10.x`~~

Nope, already on the latest `component-builder`

**Comment by ajainarayanan** [comment]
:+1:

**Comment by sankargorthi** [comment]
I was wrong. This already exists in this task. Updated the readme to reflect this.

https://github.com/anthonyshort/grunt-component-build/pull/25
