### ISSUE TITLE
Feature request - converting templates

### ISSUE THREAD

**Issue by rogerz** [anthonyshort/grunt-component-build#28]
Could this plugin convert templates files specified in `component.json` automatically to `template.js`?

**Comment by rogerz** [comment]
It seems I can do it with `component-html`. Thanks.

**Comment by anthonyshort** [comment]
With the latest version of Component you don't need a plugin for this either, it's built-in

**Comment by rogerz** [comment]
Is that true that the `template.html.js` will be an intermediate file only? I didn't find it after build but the content seems to be included in `build.js`

**Comment by anthonyshort** [comment]
Yeah it's included in the build, it doesn't create a .js file for it.

**Comment by anthonyshort** [comment]
And it can be anything, not just HTML. It just turns everything in `templates` into strings and adds them to the build
