### ISSUE TITLE
exclude dir option

### ISSUE THREAD

**Issue by azhang** [anthonyshort/grunt-component-build#32]
Since I have my component.json directory in my project root directory, I have set `src: './'`.

```
componentbuild: {
  options: {
    dev: true, 
    sourceUrls: true,
    configure: function(builder){
      var jade = require('component-jade'); 
      builder.use(jade); 
    }
  }, 
  components: {
    options: {}, 
    src: './', 
    dest: 'build/js'
  }
}
```

However, when I `grunt watch` and make a change, it gives me

```
Warning: EMFILE, too many open files
```

This is fixed when I move my component.json file to ./client, but that means to `component install` I'd have to `cd client` first which seems unintuitive. Is there a way to exclude node_modules, which is probably the reason for the EMFILE warning?

**Comment by kewah** [comment]
You can increase the limit to avoid this error 
https://github.com/gruntjs/grunt-contrib-watch#how-do-i-fix-the-error-emfile-too-many-opened-files

**Comment by azhang** [comment]
Sure this is an alright workaround, but it'd be better to only watch the `paths` specified in `./component.json` to reduce memory/cpu usage.

**Comment by kewah** [comment]
closed for inactivity
