### ISSUE TITLE
component/builder updated to 0.12.0

### ISSUE THREAD

**Issue by azhang** [anthonyshort/grunt-component-build#36]

**Comment by kewah** [comment]
The API has changed between 0.10.x and 0.12.x. I prefer to wait an update of the documentation to be sure they won't change again. See builder readme 

> the 0.12.x release breaks backwards compat, and requires additional changes before we'll be re-documenting.

**Comment by wyuenho** [comment]
They've done a major refactoring and lots of old stuff are now obsolete.

This project needs to upgrade to https://github.com/component/builder2.js

**Comment by kewah** [comment]
Yep, it's on my todo :)
Especially since component is reaching v1.0.0

**Comment by azhang** [comment]
@wyuenho component/builder.js and component/builder2.js are different projects.

edit: but it seems that builder2.js has much more activity than builder.js. It might be a good idea to switch this project to using builder2, or have it as an option.

**Comment by kewah** [comment]
I plan to use https://github.com/component/build.js which is used by `component-build(1)`

**Comment by wyuenho** [comment]
Nope and nope. Check again.

https://www.npmjs.org/package/component-builder

Builder2 has taken over the builder package name. It's a rewrite.

**Comment by kewah** [comment]
@wyuenho component/build.js uses builder2. See https://github.com/component/build.js/blob/master/package.json#L15

> This is a thin wrapper around component-builder2.

I think it is better to stick to `component-build(1)` functionalities.

**Comment by wyuenho** [comment]
Ahh ok. That makes sense!

**Comment by azhang** [comment]
Wow, I totally missed the update to builder2. :+1:
