### ISSUE TITLE
Fatal error: failed to lookup "xxx"'s dependency

### ISSUE THREAD

**Issue by prewk** [anthonyshort/grunt-component-build#39]
Hi!
If I run `component build` in my component's directory, which has some dependencies:

```
"dependencies": {
    "prewk/angular.js-component": "1.2.16b",
    "prewk/bootstrap-component": "3.1.1b",
    "prewk/restangular-component": "1.3.1b",
    "angular-ui/ui-router": "0.2.10",
    "lodash/lodash": "2.4.1",
},
```

..the component gets built just fine.

When I try to use grunt-component-build, however, with a Gruntfile like this:

```
componentbuild: {
    options: {
        dev: true,
        sourceUrls: true,
        copy: true
    },
    xxx: {
        options: {
            name: 'xxx'
        },
        src: 'front-end/xxx',
        dest: 'public/build/xxx'
    }
},
```

(The component is at `./front-end/xxx` and I want to build to `./public/build/xxx`)

..I get this error:

```
Fatal error: failed to lookup "xxx"'s dependency "prewk-angular.js-component"
```

The error must be occurring when reading `component.json`, because if I erase out my whole `.main` file `index.js` it doesn't care, the same error message persists.

Any pointers?

**Comment by kewah** [comment]
Which version of component and grunt-component-build do you use ?

**Comment by prewk** [comment]
```
"component": "~1.0.0-rc5",
"grunt-component-build": "~0.4.3"
```

**Comment by kewah** [comment]
I have pushed a new version early in this afternoon to support the new component API (v1.0.0). If you update to the version 0.5.0 it may fix your issue. 
Dependencies are not managed the same way on component < 0.12.0 and component 1.0.0.

**Comment by prewk** [comment]
:smiley: Now it works! Thanks!
