### ISSUE TITLE
No remote found for dependency

### ISSUE THREAD

**Issue by paulyoung** [anthonyshort/grunt-component-build#40]
My `Gruntfile.coffee` file includes this:

``` coffeescript
  componentbuild:
    'ccss-compiler':
      options:
        name: 'ccss-compiler'
        install: true
      src: '.'
      dest: 'browser'
      scripts: true
      styles: false
```

All was working fine until I added this to my `component.json file`:

``` json
{
  "dependencies": {
    "the-gss/error-reporter": "*"
  }
}
```

Now when the task runs I get the following error:

``` sh
Fatal error: no remote found for dependency "the-gss/error-reporter".
```

I can reach https://raw.githubusercontent.com/the-gss/error-reporter/master/component.json and running `component install` then `component build -o browser` with component v0.19.9 works fine.

I'm using grunt-component-build v0.5.0

**Comment by kewah** [comment]
grunt-component-build v0.5.0 isn't compatible with older versions of component.
If you install the latest component version (`npm i -g component@1.0.0-rc5`) it should works

**Comment by paulyoung** [comment]
I only installed component to see if I was doing something wrong with my configuration. I rarely install global node modules and mostly add them as dependencies in my package.json file.

Doesn't grunt-component-build install component somewhere in the dependency tree? It seems weird that I'd also need add component as a dependency too.

**Comment by paulyoung** [comment]
FWIW, I tried verifying my configuration using 0.19.9 because it was the most recent version on npm:  https://www.npmjs.org/package/component

**Comment by paulyoung** [comment]
I was skeptical as to why it would work but tried anyway with `npm install -g component@1.0.0-rc5` and got the same issue.

Could it be that some dependency of **grunt-component-build** is using an older version of **component**?

**Comment by kewah** [comment]
Yes, sorry, I don't know what I had in mind :/

I've pushed a test with your component as a dep. The build doesn't fail on my side. (the component will be installed in `test/fixtures/components/`).
You can checkout the branch `bug/gss-error-reporter` and run `grunt componentbuild:test_default` or run the tests `npm test`.

**Comment by paulyoung** [comment]
Here's what happens for me on that branch when running `npm test`:

``` sh
Running "shell:expected" (shell) task
rm -fr test/expected
cd test/fixtures; ../../node_modules/component/bin/component-build -o test/expected -n dev --dev -o ../expected/dev

       error : failed to lookup "src"'s dependency "component-emitter"

make: *** [expected-dev] Error 1
Warning: Command failed:
       error : failed to lookup "src"'s dependency "component-emitter"

make: * [expected-dev] Error 1
 Use --force to continue.

Aborted due to warnings.
npm ERR! weird error 6
npm ERR! not ok code 0
```

**Comment by paulyoung** [comment]
`grunt componentbuild:test_default` does appear to work correctly though.

Investigating now.

**Comment by kewah** [comment]
Ok, then even with component-build(1) it doesn't work for you. 

Is there anything installed in `test/fixtures/components` ?
I guess it's an issue with [component/resolver.js](https://github.com/component/resolver.js) and `install` option.

**Comment by paulyoung** [comment]
Yeah, `component/emitter` and `the-gss/error-reporter` get installed.

**Comment by paulyoung** [comment]
Trying this new branch in my real project to see if there's any change.

**Comment by paulyoung** [comment]
Same issue with this in my `package.json` file:

``` json
{
  "grunt-component-build": "git://github.com/anthonyshort/grunt-component-build.git#bug/gss-error-reporter"
}
```

**Comment by paulyoung** [comment]
Just found that if I reduce my component.json file to **only** this:

``` javascript
{
  "dependencies": {
    "the-gss/error-reporter": "*"
  }
}
```

the install goes fine. (Obviously it fails after that).

It must be related to something in the existing package.json file.

**Comment by paulyoung** [comment]
I removed this and everything works now:

``` json
{
  "remotes": [
    "https://raw.githubusercontent.com"
  ]
}
```

The [component.json spec](https://github.com/component/spec/blob/master/component.json/specifications.md) does say this:

> The **public** component **must not** contain any `remotes`.

Maybe this project used to be private and it got left over from that, or maybe this confused things somehow:

> The remote "https://raw.github.com" is implied and automatically added to the _end_ of the `remotes` array at all times. To increase performance if most of your components originate from GitHub it is recommended to add it as the _first_ remote so that it is hit before the others

I'm not sure if the spec document is out of date and now https://raw.githubusercontent.com is used instead of https://raw.github.com.

**Comment by paulyoung** [comment]
But, why would using `component` manually work?

**Comment by kewah** [comment]
The api has changed with component v1.0. It doesn't install dependencies the same way.
I think if you install component@1.0.0-rc5, you will get the same error when you run manually `component build`

**Comment by paulyoung** [comment]
Thanks for the explanation!
