### ISSUE TITLE
browser vs browsers

### ISSUE THREAD

**Issue by ghost** [anthonyshort/grunt-component-build#41]
It caught my eye that component build expects a `browsers` option (plural), when the docs refer to a `browser` option. 

When running componentbuild with these options:

``` javascript
options: {
  name: 'main',
  browser: ["last 3 version","> 1%"],
  install: true,
  copy: true
}
```

and with the `--verbose` flag, this is the output:

```
Options: name="main", install, verbose, require, copy, scripts,
styles, files, standalone="", prefix="", browsers="", browser=["last 3 version","> 1%"]
```

Notice the presence of both `browsers` and `browser`. It seems that `browsers` is actually the correct key for defining the targets for autoprefixing?

**Comment by kewah** [comment]
Hi,

You are right, `browsers` is the correct key. 
I've updated the readme
Thanks
