### ISSUE TITLE
Move built-in plugins into separate projects

### ISSUE THREAD

**Issue by kewah** [anthonyshort/grunt-component-build#6]
Hi,

I think that built-in plugins should be in separate projects/repos: easiest to maintain, to tests (btw i'm currently adding unit tests) and so, in case you need a plugin you just need to add it as a dependency to your project.
Kind of like what Grunt is doing for the version 0.4.

**Comment by anthonyshort** [comment]
Yep, there is already one out there for Coffeescript as well. I might pull the string-to-js plugin out and just point to those.

**Comment by pfraces** [comment]
+1

**Comment by anthonyshort** [comment]
Done!
